"""empty message

Revision ID: 82e6a7fd3e92
Revises: 3c04c3a92bc9
Create Date: 2018-02-07 21:31:09.953964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82e6a7fd3e92'
down_revision = '3c04c3a92bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'date_of_birth')
    op.drop_column('book', 'publish_date')
    op.drop_column('book', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('publish_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('date_of_birth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
